export const INDIAN_STATIONS = [
  { name: "Agra", code: "AGC", state: "Uttar Pradesh" },
  { name: "Ahmedabad", code: "ADI", state: "Gujarat" },
  { name: "Ajmer", code: "AII", state: "Rajasthan" },
  { name: "Allahabad (Prayagraj)", code: "PRYJ", state: "Uttar Pradesh" },
  { name: "Amritsar", code: "ASR", state: "Punjab" },
  { name: "Bangalore", code: "SBC", state: "Karnataka" },
  { name: "Bhopal", code: "BPL", state: "Madhya Pradesh" },
  { name: "Bhubaneswar", code: "BBS", state: "Odisha" },
  { name: "Bilaspur", code: "BSP", state: "Chhattisgarh" },
  { name: "Chandigarh", code: "CDG", state: "Chandigarh" },
  { name: "Chennai", code: "MAS", state: "Tamil Nadu" },
  { name: "Coimbatore", code: "CBE", state: "Tamil Nadu" },
  { name: "Dehradun", code: "DDN", state: "Uttarakhand" },
  { name: "Dhanbad", code: "DHN", state: "Jharkhand" },
  { name: "Ernakulam", code: "ERS", state: "Kerala" },
  { name: "Gaya", code: "GAYA", state: "Bihar" },
  { name: "Gorakhpur", code: "GKP", state: "Uttar Pradesh" },
  { name: "Guntur", code: "GNT", state: "Andhra Pradesh" },
  { name: "Guwahati", code: "GHY", state: "Assam" },
  { name: "Gwalior", code: "GWL", state: "Madhya Pradesh" },
  { name: "Haridwar", code: "HW", state: "Uttarakhand" },
  { name: "Hyderabad", code: "HYB", state: "Telangana" },
  { name: "Indore", code: "INDB", state: "Madhya Pradesh" },
  { name: "Jabalpur", code: "JBP", state: "Madhya Pradesh" },
  { name: "Jaipur", code: "JP", state: "Rajasthan" },
  { name: "Jammu", code: "JAT", state: "Jammu & Kashmir" },
  { name: "Jhansi (VGLJ)", code: "VGLJ", state: "Uttar Pradesh" },
  { name: "Jodhpur", code: "JU", state: "Rajasthan" },
  { name: "Kanpur", code: "CNB", state: "Uttar Pradesh" },
  { name: "Kolkata", code: "HWH", state: "West Bengal" },
  { name: "Kota", code: "KOTA", state: "Rajasthan" },
  { name: "Lucknow", code: "LKO", state: "Uttar Pradesh" },
  { name: "Ludhiana", code: "LDH", state: "Punjab" },
  { name: "Madurai", code: "MDU", state: "Tamil Nadu" },
  { name: "Mumbai", code: "CSMT", state: "Maharashtra" },
  { name: "Nagpur", code: "NGP", state: "Maharashtra" },
  { name: "New Delhi", code: "NDLS", state: "Delhi" },
  { name: "Patna", code: "PNBE", state: "Bihar" },
  { name: "Pune", code: "PUNE", state: "Maharashtra" },
  { name: "Raipur", code: "R", state: "Chhattisgarh" },
  { name: "Rajkot", code: "RJT", state: "Gujarat" },
  { name: "Ranchi", code: "RNC", state: "Jharkhand" },
  { name: "Secunderabad", code: "SC", state: "Telangana" },
  { name: "Shimla", code: "SML", state: "Himachal Pradesh" },
  { name: "Surat", code: "ST", state: "Gujarat" },
  { name: "Tatanagar", code: "TATA", state: "Jharkhand" },
  { name: "Thiruvananthapuram", code: "TVC", state: "Kerala" },
  { name: "Tirupati", code: "TPTY", state: "Andhra Pradesh" },
  { name: "Udaipur", code: "UDZ", state: "Rajasthan" },
  { name: "Vadodara", code: "BRC", state: "Gujarat" },
  { name: "Varanasi", code: "BSB", state: "Uttar Pradesh" },
  { name: "Vijayawada", code: "BZA", state: "Andhra Pradesh" },
  { name: "Visakhapatnam", code: "VSKP", state: "Andhra Pradesh" }
];
